-- Starter ingredients, so matching works from day one. Edit or add to them in the app
-- (menu -> ingredients). density is grams per ml (flour ~0.52 = 125 g a cup);
-- unit_weight is grams per item (an onion ~150 g); shelf_days sets the default use-by.
INSERT INTO ingredients (name, aliases, category, default_unit, aisle, storage, density, unit_weight, shelf_days, always_have) VALUES
  ('onion', 'onions, brown onion, white onion, yellow onion', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 150, 30, 0),
  ('red onion', '', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 150, 30, 0),
  ('spring onion', 'scallion, green onion, salad onion', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 15, 7, 0),
  ('shallot', 'shallots, banana shallot', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 40, 30, 0),
  ('garlic', 'garlic bulb, garlic clove, garlic cloves', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 50, 30, 0),
  ('ginger', 'fresh ginger, root ginger, ginger root', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 21, 0),
  ('potato', 'potatoes, white potatoes, maris piper, new potatoes, baby potatoes', 'vegetables', 'g', 'fruit & veg', 'cupboard', NULL, 200, 21, 0),
  ('sweet potato', 'yam', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 250, 21, 0),
  ('carrot', 'carrots', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 70, 21, 0),
  ('celery', 'celery stick, celery sticks, stick celery', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 40, 14, 0),
  ('courgette', 'zucchini, courgettes', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 200, 7, 0),
  ('aubergine', 'eggplant', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 300, 7, 0),
  ('pepper', 'bell pepper, red pepper, green pepper, yellow pepper, capsicum', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 160, 10, 0),
  ('chilli', 'chili, red chilli, green chilli, chile, bird''s eye chilli', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 10, 10, 0),
  ('tomato', 'tomatoes, vine tomatoes, salad tomatoes', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 100, 7, 0),
  ('cherry tomatoes', 'cherry tomato, baby plum tomatoes, grape tomatoes', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 7, 0),
  ('mushrooms', 'mushroom, chestnut mushrooms, button mushrooms, closed cup mushrooms', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('broccoli', 'tenderstem broccoli, tenderstem, broccoli florets', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, 350, 6, 0),
  ('cauliflower', '', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 600, 7, 0),
  ('spinach', 'baby spinach, spinach leaves', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 4, 0),
  ('lettuce', 'little gem, iceberg lettuce, romaine, salad leaves, mixed leaves', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 300, 5, 0),
  ('rocket', 'arugula', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 4, 0),
  ('kale', 'cavolo nero', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('cabbage', 'red cabbage, savoy cabbage, white cabbage', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 900, 14, 0),
  ('leek', 'leeks', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 200, 10, 0),
  ('cucumber', '', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 300, 7, 0),
  ('green beans', 'fine beans, french beans', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('butternut squash', 'squash', 'vegetables', 'count', 'fruit & veg', 'cupboard', NULL, 1000, 30, 0),
  ('beansprouts', 'bean sprouts', 'vegetables', 'g', 'fruit & veg', 'fridge', NULL, NULL, 3, 0),
  ('pak choi', 'bok choy', 'vegetables', 'count', 'fruit & veg', 'fridge', NULL, 150, 5, 0),
  ('avocado', 'avocados', 'fruit', 'count', 'fruit & veg', 'cupboard', NULL, 170, 4, 0),
  ('lemon', 'lemons', 'fruit', 'count', 'fruit & veg', 'fridge', NULL, 100, 21, 0),
  ('lime', 'limes', 'fruit', 'count', 'fruit & veg', 'fridge', NULL, 60, 21, 0),
  ('apple', 'apples', 'fruit', 'count', 'fruit & veg', 'fridge', NULL, 180, 21, 0),
  ('banana', 'bananas', 'fruit', 'count', 'fruit & veg', 'cupboard', NULL, 120, 5, 0),
  ('orange', 'oranges', 'fruit', 'count', 'fruit & veg', 'fridge', NULL, 150, 14, 0),
  ('strawberries', 'strawberry', 'fruit', 'g', 'fruit & veg', 'fridge', NULL, NULL, 4, 0),
  ('blueberries', 'blueberry', 'fruit', 'g', 'fruit & veg', 'fridge', NULL, NULL, 6, 0),
  ('raspberries', 'raspberry', 'fruit', 'g', 'fruit & veg', 'fridge', NULL, NULL, 3, 0),
  ('grapes', 'grape', 'fruit', 'g', 'fruit & veg', 'fridge', NULL, NULL, 7, 0),
  ('fresh coriander', 'coriander leaves, cilantro, coriander, fresh cilantro', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('fresh parsley', 'parsley, flat-leaf parsley, flat leaf parsley, curly parsley', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('fresh basil', 'basil, basil leaves', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('fresh mint', 'mint, mint leaves', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('fresh thyme', 'thyme sprigs, fresh thyme sprigs', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 7, 0),
  ('rosemary', 'fresh rosemary, rosemary sprigs', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 10, 0),
  ('chives', 'fresh chives', 'herbs', 'g', 'fruit & veg', 'fridge', NULL, NULL, 5, 0),
  ('chicken breast', 'chicken breasts, chicken breast fillets, chicken fillets', 'meat', 'g', 'meat & fish', 'fridge', NULL, 150, 2, 0),
  ('chicken thighs', 'chicken thigh, boneless chicken thighs, chicken thigh fillets', 'meat', 'g', 'meat & fish', 'fridge', NULL, 120, 2, 0),
  ('whole chicken', 'chicken', 'meat', 'count', 'meat & fish', 'fridge', NULL, 1500, 2, 0),
  ('beef mince', 'minced beef, ground beef, mince', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 2, 0),
  ('steak', 'sirloin steak, ribeye steak, rump steak, beef steak, sirloin, ribeye', 'meat', 'count', 'meat & fish', 'fridge', NULL, 250, 3, 0),
  ('stewing beef', 'braising steak, diced beef, beef chuck', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 2, 0),
  ('sausages', 'pork sausages, sausage', 'meat', 'count', 'meat & fish', 'fridge', NULL, 60, 4, 0),
  ('bacon', 'bacon rashers, streaky bacon, back bacon, lardons, pancetta', 'meat', 'g', 'meat & fish', 'fridge', NULL, 25, 7, 0),
  ('chorizo', '', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 21, 0),
  ('pork chops', 'pork chop', 'meat', 'count', 'meat & fish', 'fridge', NULL, 200, 3, 0),
  ('pork mince', 'minced pork, ground pork', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 2, 0),
  ('turkey mince', 'minced turkey, ground turkey', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 2, 0),
  ('lamb mince', 'minced lamb, ground lamb', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 2, 0),
  ('ham', 'sliced ham, cooked ham', 'meat', 'g', 'meat & fish', 'fridge', NULL, NULL, 5, 0),
  ('salmon', 'salmon fillet, salmon fillets', 'fish', 'count', 'meat & fish', 'fridge', NULL, 120, 2, 0),
  ('white fish', 'cod, haddock, cod fillet, cod fillets, haddock fillet, white fish fillets', 'fish', 'count', 'meat & fish', 'fridge', NULL, 130, 2, 0),
  ('prawns', 'shrimp, king prawns, raw prawns, cooked prawns', 'fish', 'g', 'frozen', 'freezer', NULL, NULL, 90, 0),
  ('tuna', 'tinned tuna, canned tuna, tuna chunks', 'fish', 'count', 'tins & jars', 'cupboard', NULL, 145, 730, 0),
  ('tofu', 'firm tofu, extra firm tofu', 'other', 'g', 'chilled', 'fridge', NULL, NULL, 7, 0),
  ('milk', 'whole milk, semi-skimmed milk, skimmed milk, semi skimmed milk', 'dairy', 'ml', 'dairy & eggs', 'fridge', 1.03, NULL, 7, 0),
  ('butter', 'unsalted butter, salted butter', 'dairy', 'g', 'dairy & eggs', 'fridge', 0.96, NULL, 30, 0),
  ('eggs', 'egg, large eggs, medium eggs, free-range eggs, free range eggs', 'eggs', 'count', 'dairy & eggs', 'fridge', NULL, 60, 21, 0),
  ('cheddar', 'cheddar cheese, cheese, grated cheese, mature cheddar, grated cheddar', 'dairy', 'g', 'dairy & eggs', 'fridge', 0.45, NULL, 21, 0),
  ('parmesan', 'parmesan cheese, parmigiano reggiano, grana padano, grated parmesan', 'dairy', 'g', 'dairy & eggs', 'fridge', 0.4, NULL, 30, 0),
  ('mozzarella', 'mozzarella ball, buffalo mozzarella', 'dairy', 'g', 'dairy & eggs', 'fridge', NULL, 125, 5, 0),
  ('feta', 'feta cheese', 'dairy', 'g', 'dairy & eggs', 'fridge', NULL, NULL, 7, 0),
  ('halloumi', '', 'dairy', 'g', 'dairy & eggs', 'fridge', NULL, NULL, 14, 0),
  ('greek yoghurt', 'greek yogurt, yoghurt, yogurt, natural yoghurt, natural yogurt, plain yogurt', 'dairy', 'g', 'dairy & eggs', 'fridge', 1.05, NULL, 10, 0),
  ('double cream', 'heavy cream, whipping cream, cream, heavy whipping cream', 'dairy', 'ml', 'dairy & eggs', 'fridge', 1.0, NULL, 5, 0),
  ('single cream', 'light cream', 'dairy', 'ml', 'dairy & eggs', 'fridge', 1.0, NULL, 5, 0),
  ('sour cream', 'soured cream', 'dairy', 'ml', 'dairy & eggs', 'fridge', 1.0, NULL, 10, 0),
  ('creme fraiche', 'crème fraîche', 'dairy', 'ml', 'dairy & eggs', 'fridge', 1.0, NULL, 10, 0),
  ('cream cheese', 'soft cheese, philadelphia', 'dairy', 'g', 'dairy & eggs', 'fridge', NULL, NULL, 10, 0),
  ('bread', 'loaf, sliced bread, sourdough, white bread, wholemeal bread', 'bread', 'count', 'bakery', 'cupboard', NULL, 800, 5, 0),
  ('tortilla wraps', 'tortillas, wraps, flour tortillas, tortilla', 'bread', 'count', 'bakery', 'cupboard', NULL, 60, 10, 0),
  ('pitta', 'pitta bread, pita, pita bread', 'bread', 'count', 'bakery', 'cupboard', NULL, 60, 5, 0),
  ('naan', 'naan bread, naans', 'bread', 'count', 'bakery', 'cupboard', NULL, 120, 5, 0),
  ('burger buns', 'buns, brioche buns, bread rolls', 'bread', 'count', 'bakery', 'cupboard', NULL, 60, 5, 0),
  ('pasta', 'spaghetti, penne, fusilli, linguine, tagliatelle, rigatoni, macaroni, dried pasta, orzo', 'grains', 'g', 'pasta, rice & grains', 'cupboard', NULL, NULL, 730, 0),
  ('rice', 'basmati rice, long grain rice, jasmine rice, white rice, brown rice', 'grains', 'g', 'pasta, rice & grains', 'cupboard', 0.85, NULL, 730, 0),
  ('risotto rice', 'arborio rice, arborio, carnaroli', 'grains', 'g', 'pasta, rice & grains', 'cupboard', 0.85, NULL, 730, 0),
  ('noodles', 'egg noodles, rice noodles, udon noodles, ramen noodles', 'grains', 'g', 'pasta, rice & grains', 'cupboard', NULL, NULL, 365, 0),
  ('couscous', '', 'grains', 'g', 'pasta, rice & grains', 'cupboard', 0.76, NULL, 365, 0),
  ('oats', 'rolled oats, porridge oats', 'grains', 'g', 'pasta, rice & grains', 'cupboard', 0.38, NULL, 365, 0),
  ('quinoa', '', 'grains', 'g', 'pasta, rice & grains', 'cupboard', 0.72, NULL, 365, 0),
  ('red lentils', 'lentils, split red lentils', 'grains', 'g', 'pasta, rice & grains', 'cupboard', 0.8, NULL, 730, 0),
  ('tinned tomatoes', 'chopped tomatoes, canned tomatoes, tinned chopped tomatoes, plum tomatoes, crushed tomatoes, diced tomatoes, canned chopped tomatoes', 'tins', 'count', 'tins & jars', 'cupboard', 1.03, 400, 730, 0),
  ('passata', 'tomato passata, sieved tomatoes', 'tins', 'ml', 'tins & jars', 'cupboard', 1.03, NULL, 365, 0),
  ('tomato puree', 'tomato purée, tomato paste', 'tins', 'g', 'tins & jars', 'cupboard', 1.1, NULL, 365, 0),
  ('coconut milk', 'tinned coconut milk, canned coconut milk, light coconut milk', 'tins', 'count', 'tins & jars', 'cupboard', 1.0, 400, 730, 0),
  ('chickpeas', 'chickpea, tinned chickpeas, garbanzo beans', 'tins', 'count', 'tins & jars', 'cupboard', NULL, 400, 730, 0),
  ('kidney beans', 'red kidney beans', 'tins', 'count', 'tins & jars', 'cupboard', NULL, 400, 730, 0),
  ('black beans', '', 'tins', 'count', 'tins & jars', 'cupboard', NULL, 400, 730, 0),
  ('butter beans', 'cannellini beans, white beans, haricot beans', 'tins', 'count', 'tins & jars', 'cupboard', NULL, 400, 730, 0),
  ('baked beans', '', 'tins', 'count', 'tins & jars', 'cupboard', NULL, 415, 730, 0),
  ('stock', 'chicken stock, vegetable stock, beef stock, stock cube, stock cubes, broth, bouillon, stock pot', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.0, 500, 365, 0),
  ('peanut butter', '', 'spreads', 'g', 'tins & jars', 'cupboard', 1.08, NULL, 180, 0),
  ('honey', '', 'spreads', 'g', 'tins & jars', 'cupboard', 1.42, NULL, 730, 0),
  ('jam', 'strawberry jam, raspberry jam', 'spreads', 'g', 'tins & jars', 'cupboard', 1.3, NULL, 180, 0),
  ('plain flour', 'flour, all-purpose flour, all purpose flour', 'baking', 'g', 'baking', 'cupboard', 0.52, NULL, 365, 0),
  ('self-raising flour', 'self raising flour, self-rising flour', 'baking', 'g', 'baking', 'cupboard', 0.52, NULL, 365, 0),
  ('bread flour', 'strong white flour, strong bread flour', 'baking', 'g', 'baking', 'cupboard', 0.54, NULL, 365, 0),
  ('caster sugar', 'sugar, granulated sugar, white sugar, superfine sugar', 'baking', 'g', 'baking', 'cupboard', 0.83, NULL, 730, 0),
  ('brown sugar', 'light brown sugar, dark brown sugar, soft brown sugar, muscovado sugar', 'baking', 'g', 'baking', 'cupboard', 0.92, NULL, 730, 0),
  ('icing sugar', 'powdered sugar, confectioners sugar, confectioners'' sugar', 'baking', 'g', 'baking', 'cupboard', 0.5, NULL, 730, 0),
  ('baking powder', '', 'baking', 'g', 'baking', 'cupboard', 0.8, NULL, 365, 0),
  ('bicarbonate of soda', 'baking soda, bicarb', 'baking', 'g', 'baking', 'cupboard', 0.92, NULL, 730, 0),
  ('vanilla extract', 'vanilla, vanilla essence', 'baking', 'ml', 'baking', 'cupboard', 1.0, NULL, 730, 0),
  ('cocoa powder', 'cocoa', 'baking', 'g', 'baking', 'cupboard', 0.42, NULL, 365, 0),
  ('dark chocolate', 'chocolate, chocolate chips, milk chocolate', 'baking', 'g', 'baking', 'cupboard', NULL, NULL, 365, 0),
  ('cornflour', 'cornstarch, corn flour', 'baking', 'g', 'baking', 'cupboard', 0.53, NULL, 730, 0),
  ('yeast', 'dried yeast, fast action yeast, instant yeast', 'baking', 'g', 'baking', 'cupboard', NULL, NULL, 365, 0),
  ('pine nuts', '', 'nuts', 'g', 'baking', 'cupboard', 0.57, NULL, 180, 0),
  ('cashews', 'cashew nuts', 'nuts', 'g', 'baking', 'cupboard', 0.55, NULL, 180, 0),
  ('almonds', 'flaked almonds, ground almonds', 'nuts', 'g', 'baking', 'cupboard', 0.4, NULL, 180, 0),
  ('salt', 'sea salt, table salt, flaky salt, kosher salt, sea salt flakes, salt and pepper, salt & pepper, salt and black pepper, salt and freshly ground black pepper', 'spices', 'g', 'herbs & spices', 'spice rack', 1.2, NULL, 3650, 1),
  ('black pepper', 'ground black pepper, freshly ground black pepper, black peppercorns, peppercorns', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 1),
  ('white pepper', 'ground white pepper', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('ground cumin', 'cumin, cumin seeds', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('ground coriander', 'coriander seeds', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('paprika', 'smoked paprika, sweet paprika', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('chilli flakes', 'red pepper flakes, crushed chillies, dried chilli flakes, chili flakes', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('chilli powder', 'cayenne pepper, cayenne, chili powder', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('turmeric', 'ground turmeric', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('garam masala', '', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('curry powder', '', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('cinnamon', 'ground cinnamon, cinnamon stick', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('dried oregano', 'oregano', 'spices', 'g', 'herbs & spices', 'spice rack', 0.3, NULL, 730, 0),
  ('dried thyme', 'thyme', 'spices', 'g', 'herbs & spices', 'spice rack', 0.3, NULL, 730, 0),
  ('mixed herbs', 'italian seasoning, dried mixed herbs, herbes de provence', 'spices', 'g', 'herbs & spices', 'spice rack', 0.3, NULL, 730, 0),
  ('bay leaves', 'bay leaf', 'spices', 'count', 'herbs & spices', 'spice rack', NULL, NULL, 730, 0),
  ('nutmeg', 'ground nutmeg', 'spices', 'g', 'herbs & spices', 'spice rack', 0.5, NULL, 730, 0),
  ('olive oil', 'extra virgin olive oil, extra-virgin olive oil', 'oils', 'ml', 'oils & sauces', 'cupboard', 0.91, NULL, 365, 1),
  ('vegetable oil', 'sunflower oil, rapeseed oil, oil, cooking oil, canola oil, neutral oil', 'oils', 'ml', 'oils & sauces', 'cupboard', 0.92, NULL, 365, 1),
  ('sesame oil', 'toasted sesame oil', 'oils', 'ml', 'oils & sauces', 'cupboard', 0.92, NULL, 365, 0),
  ('soy sauce', 'light soy sauce, dark soy sauce, tamari', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.2, NULL, 365, 0),
  ('fish sauce', '', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.2, NULL, 365, 0),
  ('worcestershire sauce', '', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.1, NULL, 365, 0),
  ('balsamic vinegar', '', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.1, NULL, 730, 0),
  ('vinegar', 'white wine vinegar, red wine vinegar, cider vinegar, apple cider vinegar, rice vinegar', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.0, NULL, 730, 0),
  ('dijon mustard', 'mustard, wholegrain mustard, english mustard', 'sauces', 'g', 'oils & sauces', 'fridge', 1.1, NULL, 180, 0),
  ('mayonnaise', 'mayo', 'sauces', 'g', 'oils & sauces', 'fridge', 0.95, NULL, 60, 0),
  ('ketchup', 'tomato ketchup', 'sauces', 'g', 'oils & sauces', 'cupboard', 1.15, NULL, 180, 0),
  ('hot sauce', 'sriracha, tabasco', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.1, NULL, 365, 0),
  ('oyster sauce', '', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.2, NULL, 365, 0),
  ('hoisin sauce', 'hoisin', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.2, NULL, 365, 0),
  ('mirin', 'rice wine, chinese cooking wine, shaoxing wine, shaoxing rice wine', 'sauces', 'ml', 'oils & sauces', 'cupboard', 1.0, NULL, 365, 0),
  ('pesto', 'green pesto, basil pesto', 'sauces', 'g', 'tins & jars', 'fridge', NULL, NULL, 7, 0),
  ('curry paste', 'thai red curry paste, thai green curry paste, red curry paste, green curry paste', 'sauces', 'g', 'tins & jars', 'fridge', NULL, NULL, 30, 0),
  ('orange juice', 'juice, apple juice', 'drinks', 'ml', 'drinks', 'fridge', 1.04, NULL, 7, 0),
  ('white wine', 'dry white wine', 'drinks', 'ml', 'drinks', 'cupboard', 1.0, NULL, 5, 0),
  ('red wine', '', 'drinks', 'ml', 'drinks', 'cupboard', 1.0, NULL, 5, 0),
  ('frozen peas', 'peas, garden peas, petits pois', 'vegetables', 'g', 'frozen', 'freezer', NULL, NULL, 180, 0),
  ('sweetcorn', 'corn, corn kernels, tinned sweetcorn', 'vegetables', 'g', 'tins & jars', 'cupboard', 0.7, NULL, 365, 0),
  ('ice cream', '', 'frozen', 'ml', 'frozen', 'freezer', 0.55, NULL, 180, 0),
  ('water', 'cold water, warm water, boiling water, hot water', 'other', 'ml', 'other', 'cupboard', 1.0, NULL, NULL, 1),
  ('washing up liquid', 'dish soap', 'household', 'count', 'household', 'cupboard', NULL, NULL, NULL, 0),
  ('kitchen roll', 'paper towels', 'household', 'count', 'household', 'cupboard', NULL, NULL, NULL, 0),
  ('bin bags', 'bin liners', 'household', 'count', 'household', 'cupboard', NULL, NULL, NULL, 0),
  ('dishwasher tablets', '', 'household', 'count', 'household', 'cupboard', NULL, NULL, NULL, 0),
  ('toilet roll', 'toilet paper', 'household', 'count', 'household', 'cupboard', NULL, NULL, NULL, 0);
