// Talent Against Humanity — card content
// Every card is a joke about recruitment and HR life in general. Blanks in
// black cards are written as "_____" and rendered as a gap in the UI.

const BLACK_CARDS = [
  "The candidate's Strong No came down to _____.",
  "New field to fill out in the interview scorecard: “_____.”",
  "The real reason this candidate has been sitting in the pipeline for six weeks: _____.",
  "The job description's most honest line: “_____.”",
  "Why the hiring manager still hasn't reviewed the shortlist: _____.",
  "Candidate's answer to “what's your main motivator?”: “_____.”",
  "Why the take-home task still hasn't been graded after six days: _____.",
  "This week's recruiting standup, summarised in one word: _____.",
  "Rejection reason selected in the ATS, technically accurate: _____.",
  "What the candidate actually did during the two-week 'thinking about it' period: _____.",
  "The personality assessment revealed: _____.",
  "Ping HR immediately — someone just _____.",
  "Why the hiring dashboard is full of errors: _____.",
  "What the final-round interview was really deciding: _____.",
  "The candidate's notice period hinged entirely on _____.",
  "Next quarter's hiring target, already slipping because of: _____.",
  "The real definition of 'culture fit': _____.",
  "Why the offer letter landed in spam, again: _____.",
  "What 'we're a family here' unofficially also means: _____.",
  "The candidate went dark right after the offer because of _____.",
  "What's actually inside the hiring manager's notes: _____.",
  "A go-to stalling phrase mid-interview: “_____.”",
  "Why the interview debrief ran forty minutes over: _____.",
  "The real acceptance criteria for this role: _____.",
  "What finally got removed from the job ad after two years: _____.",
  "The onboarding checklist forgot to mention _____.",
  "In today's standup, the update nobody asked for: _____.",
  "The candidate's self-reported 'greatest strength': _____.",
  "The real reason for the duplicate-candidate flag: _____.",
  "A subject access request just landed. First reaction: “_____.”",
  "The one thing everyone quietly exaggerates on their CV: _____.",
  "The exit interview's most memorable answer: “_____.”",
  "The candidate handled the psychometric test by _____.",
  "The reference check got awkward when they mentioned _____.",
  "The 'competitive salary' turned out to be _____.",
  "Why the recruiter can't make the 9am kickoff: _____.",
];

const WHITE_CARDS = [
  "An aptitude score nobody can explain",
  "Three consecutive Strong Nos",
  "An unread DM from the hiring manager",
  "Vibes",
  "A pipeline report that breaks every Friday",
  "Forgetting to tag the hiring manager",
  "A scorecard copy-pasted from someone else's interview",
  "The candidate quietly googling the company mid-interview",
  "Choosing chaos",
  "A job description with zero requirements and eleven 'nice to haves'",
  "“I'm a real people person”, said fourteen times in one interview",
  "Ghosting right after the offer",
  "A personality profile that says 'chaotic neutral'",
  "Sitting in the pipeline for six weeks and counting",
  "Getting rejected for academics while claiming to be top 1%",
  "A hiring dashboard stuck permanently loading",
  "The one interviewer who only asks brain teasers",
  "A 'greatest strength' that's just a participation trophy",
  "Not knowing what any of the acronyms stand for, but faking it till you make it",
  "A take-home task graded by only one very tired person",
  "“Let's take this offline”",
  "Six months of 'in progress'",
  "An interview that ran long because of small talk",
  "The same candidate flagged as a duplicate by three different people",
  "A subject access request arriving on a Friday at 5:58pm",
  "A candidate with zero self-awareness",
  "The action item that never gets actioned",
  "A scorecard that just says 'Strong Yes' with no details",
  "Being added to a group chat you never asked to be in",
  "The offer letter landing in spam, again",
  "Confidently mispronouncing the company name",
  "A candidate whose 'biggest achievement' is attendance",
  "An automation that definitely wasn't supposed to do that",
  "A req that's been open since roughly forever",
  "The candidate asking to reschedule for the fourth time",
  "A ten-minute chat that becomes forty-five",
  "Accidentally merging two different candidates in the ATS",
  "The interview decided entirely on a vibe",
  "Losing an entire afternoon to a spreadsheet",
  "The one interviewer who scores everyone a Strong Yes",
  "A cohort of hiring managers who've never opened the ATS before",
  "Being the one person in a meeting nobody remembers inviting",
  "A candidate's right-to-work paperwork built like a Jenga tower",
  "A role whose hiring manager is on leave for the next two weeks",
  "Realising the 'quick sync' is ninety minutes long",
  "A rejection email that took longer to write than the interview",
  "Three final-round interviews, three opinions, zero decisions",
  "An offer letter sent to the wrong candidate",
  "A team retro where the only feedback is silence",
  "Being told 'it's just a formality' about something that is not a formality",
  "A candidate who peaked at 'Hi, nice to meet you'",
  "A candidate who brought their own psychometric results to argue with you",
  "A scorecard with more emojis than words",
  "The reporting pipeline failing right before the meeting",
  "The reviewer who grades everything a 9 out of 10",
  "A 'quick task' that turns out to be a full afternoon",
  "A candidate's notice period that's somehow longer than their tenure",
  "A hiring manager with strong opinions and zero context",
  "Asking HR an urgent question and getting a reply three weeks later",
  "A scorecard vote of 'Yes, reluctantly'",
  "“Unlimited holiday”",
  "A LinkedIn message that opens with 'I hope this finds you well'",
  "A candidate who lists 'Microsoft Word' as a core skill",
  "Ninety-eight open tabs, all of them the same candidate",
  "A 'flat hierarchy' with seven layers of approval",
  "A reference who has never heard of the candidate",
  "The phrase 'rockstar ninja'",
  "Panic-hiring in December",
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { BLACK_CARDS, WHITE_CARDS };
}
