// Talent Against Humanity — card content
// Every card is a joke about recruitment and HR life in general. Blanks in
// black cards are written as "_____" and rendered as a gap in the UI.

const BLACK_CARDS = [
  "My candidate's CV looked great until I noticed a gap explained only by _____.",
  "What is HR's secret, off-the-record strategy for improving company culture?",
  "\"We offer competitive pay!\" translates to _____.",
  "What did I accidentally send to the entire company instead of the candidate's offer letter?",
  "The real reason the hiring manager rejected a top-tier candidate.",
  "What's the newest, most aggressive trend in quiet quitting?",
  "Instead of a salary raise, executive leadership gifted everyone _____.",
  "_____: The ultimate icebreaker for a completely silent panel interview.",
  "What's strictly forbidden to mention during a first-round phone screen?",
  "Behind every \"We'll keep your resume on file\" is _____.",
  "Why did the star developer ghost us after the final round?",
  "The newest mandatory turn-your-camera-on Zoom activity is _____.",
  "What's guaranteed to trigger an immediate, unscheduled call from Legal?",
  "Forget technical skills — we're now hiring purely based on _____.",
  "What's actually written in the redacted sections of the employee handbook?",
  "What's the fastest way to get blacklisted by the recruiting team?",
  "Our culture code explicitly bans _____.",
  "The candidate asked for a $200k base salary, but settled for _____.",
  "What's replacing the annual performance review this year?",
  "I knew the culture fit interview was over when the applicant brought up _____.",
  "What did the hiring manager demand in the job description for an entry-level role?",
  "_____: The real reason the requisition has been open for 180 days.",
  "What is leadership's latest strategy to get people back into the office?",
  "The HR department's unwritten policy regarding salary transparency.",
  "My favorite part of onboarding a remote employee is _____.",
  "What's guaranteed to make a candidate withdraw their application instantly?",
  "_____: A totally acceptable reason to fire someone on day two.",
  "The candidate's reference check revealed _____.",
  "What's hiding behind the phrase \"other duties as assigned\"?",
  "The final boss of grueling, seven-round interview processes.",
  "What's the newest perk added to our \"Industry-Leading\" benefits package?",
  "During the exit interview, the employee broke down and confessed to _____.",
  "Why is the entire HR department taking a mandatory \"Mental Health Day\"?",
  "The real reason we haven't promoted anyone in three years is _____.",
  "What's the quickest way to ruin a candidate's background check?",
  "_____: The main topic of discussion in the unmonitored Slack channel.",
  "What did the CEO say during the all-hands meeting that caused half the company to quit?",
  "Our applicant tracking system immediately rejects any resume containing _____.",
  "The candidate's portfolio was 10% actual work and 90% _____.",
  "What did the hiring manager complain about after an otherwise perfect interview?",
  "_____: The real reason we require a 4-year degree for a data entry role.",
  "What's the most toxic thing you can hear in a 1-on-1 with your manager?",
  "The candidate passed the technical assessment, but failed spectacularly at _____.",
  "Why did Legal veto the company's new diversity initiative?",
  "What's replacing actual cash bonuses this quarter?",
];

const WHITE_CARDS = [
  "A candidate who lists \"Excel expert\" but doesn't know how to sum a column.",
  "Offering a pizza party instead of market-rate compensation.",
  "Crying in a bathroom stall during open enrollment.",
  "\"Unlimited PTO\" that requires three VP approvals to take a single Friday off.",
  "Accidentally sending an internal roasting email directly to the applicant.",
  "A LinkedIn post that starts with \"I'm humbled and honored\" and ends with pure hubris.",
  "The hiring manager who wants a senior architect for entry-level pay.",
  "A candidate interviewing in a crisp suit jacket and pajama pants.",
  "Ghosting 40 applicants simultaneously.",
  "Claiming \"fast-paced environment\" to cover up complete operational chaos.",
  "A resume written entirely by ChatGPT with the prompts still left in.",
  "Passive-aggressively updating your Slack status to \"In a meeting.\"",
  "An exit interview that turns into a full-length villain monologue.",
  "The mandatory team-building exercise nobody asked for.",
  "Asking a candidate where they see themselves in five years during a terrifying global crisis.",
  "A candidate bringing their mother to a final-round interview.",
  "Rejecting an applicant because their \"vibe was off.\"",
  "Replying \"Per my previous email\" with nuclear-level hostility.",
  "Onboarding software that crashes on your very first day.",
  "A corporate wellness program consisting entirely of a meditation app subscription.",
  "Panic-hiring in December.",
  "A candidate using a fake voice filter during a video screen.",
  "Asking about the company's layoff history in the first five minutes.",
  "Requiring 10 years of experience for a software tool released last year.",
  "A candidate who turns off their camera during the interview to take another job's call.",
  "Using \"we're like a family here\" as an unprompted red flag.",
  "A candidate who submits a video resume formatted like a TikTok dance trend.",
  "An HR generalist surviving solely on iced coffee and corporate spite.",
  "Scheduling a 4:30 PM Friday meeting titled \"Quick Catch-up.\"",
  "A candidate listing their World of Warcraft guild leadership on their CV.",
  "A hiring manager who rejects anyone who didn't send a hand-written thank-you note.",
  "Accidentally posting the internal salary band publicly on LinkedIn.",
  "A standard take-home assignment that takes 40 unpaid hours to complete.",
  "Taking a candidate to lunch only for them to treat the server like trash.",
  "The VP of People wearing sunglasses indoors to hide a hangover.",
  "A candidate who sends a connection request on LinkedIn 12 seconds after applying.",
  "Promising stock options in a startup that produces nothing.",
  "A resume that is just a single QR code pointing to a personal brand song.",
  "The CEO interrupting a final interview to talk about their crypto portfolio.",
  "A background check that turns up a surprising amount of pirate activity.",
  "Faking a bad internet connection to avoid answering a technical question.",
  "A candidate who visibly googles the answer during a live coding challenge.",
  "An HR manager using ChatGPT to write empathetic layoff notifications.",
  "Accidentally joining an interview with a funny Zoom filter turned on.",
  "A candidate who answers \"What is your biggest weakness?\" with \"I care too much.\"",
  "Sending a rejection email to a candidate three years after they applied.",
  "A hiring manager who demands a \"rockstar\" but pays \"garage band\" wages.",
  "A resume that includes a high-resolution photo of the applicant's dog.",
  "Clapping along to a corporate video about \"synergy.\"",
  "A candidate who brings their spouse to negotiate their salary for them.",
  "Stealing office supplies as a form of non-equity compensation.",
  "A 15-stage interview process that ends in a position freeze.",
  "Claiming to be \"fluent in Python\" when you've only owned a pet snake.",
  "A candidate who lists \"influencer\" as their primary work history.",
  "The recruiter who sends cold LinkedIn messages to current employees of the same company.",
  "Asking \"Are you guys actually hiring, or is this a ghost job?\" in the phone screen.",
  "A candidate wearing a suit on top and swimming trunks on the bottom.",
  "Setting your Slack status to \"Active\" while taking a three-hour nap.",
  "An applicant who tries to bribe the recruiter with homemade baked goods.",
  "The hiring manager who decides within four seconds based on \"handshake firmness.\"",
  "A candidate who accidentally shares their screen showing a tab titled \"How to lie on a resume.\"",
  "A candidate who lists \"Expert in Microsoft Office\" but gets defeated by a PDF.",
  "Blaming \"payroll glitches\" for a delayed paycheck.",
  "An applicant who refers to themselves as a \"Thought Leader\" in the first paragraph.",
  "A hiring manager asking for a candidate with 15 years of experience in a 2-year-old framework.",
  "Answering a phone screen from inside a noisy Starbucks bathroom.",
  "A recruiter using \"Hey Rock Star!\" as an opening salutation.",
  "A candidate who accidentally leaves their salary expectations as \"$1,000,000.\"",
  "Taking a candidate out for coffee only for them to order a double espresso and walk out.",
  "A resume with five different font styles, three colors, and word art.",
  "An applicant who uses their former boss as a personal reference without asking.",
  "An interviewer who spends 45 minutes talking about their own career instead of asking questions.",
  "Claiming to be \"detail-oriented\" in a resume with four spelling mistakes in the header.",
  "A candidate who wears a Bluetooth earpiece during the entire panel interview.",
  "Accidentally hitting \"Reply All\" to an email thread containing sensitive feedback.",
  "A candidate who tries to negotiate for equity in a company that doesn't exist yet.",
  "An exit interview where the employee hands over a binder full of receipts.",
  "A job posting that requires a cover letter, three references, and a 1,000-word essay for an unpaid internship.",
  "An applicant who lists \"Proficient in Googling stuff\" as a core competency.",
  "A candidate who asks if the company drug tests \"for recreational stuff.\"",
  "A hiring manager rejecting a candidate because their astrology sign doesn't align with the team.",
  "A candidate whose screen share reveals an active job search browser history.",
  "The HR representative who drinks out of a mug that says \"HR: Here to Help\" with a straight face.",
  "A candidate who answers a technical question by reading directly off Wikipedia.",
  "Putting \"Works well under pressure\" on a resume after causing a complete system outage.",
  "An applicant who sends a connection request to every board member after a first-round interview.",
  "A candidate who shows up 45 minutes early and expects the interviewer to be ready.",
  "Using a fake name on a phone screen because you already work for the company under a different name.",
  "A candidate who lists \"Crisis Management\" because they survived a group project in college.",
  "An interviewer who forgets the candidate's name halfway through the interview.",
  "A candidate who asks \"So, what does this company actually do?\" in the final round.",
  "A candidate who refers to their previous boss as \"The Warden.\"",
  "An applicant who sends a thank-you note generated by ChatGPT.",
  "Asking if the company culture supports \"aggressive mid-day napping.\"",
  "A candidate who lists \"Professional Gaslighter\" as a key soft skill.",
  "An interviewer who falls asleep during a candidate's portfolio presentation.",
  "Accidentally cc'ing the candidate on an internal email that just says \"Hard pass.\"",
  "A candidate who brings their emotional support peacock to an in-person interview.",
  "An applicant who claims to be a \"synergy enthusiast.\"",
  "A hiring manager who rates candidates based entirely on their Slack emoji usage.",
  "A resume that includes a detailed list of video game achievements.",
  "An applicant who asks about the severance package during the phone screen.",
  "A candidate who responds to every question with \"That's proprietary information.\"",
  "An interviewer who asks \"If you were a kitchen appliance, what would you be?\"",
  "A candidate who tries to turn the interview into a pitch for their MLM.",
  "Using a virtual background of a private jet to hide your messy bedroom.",
  "An applicant who insists on being called \"The Solutions Guy.\"",
  "A candidate who asks if the office fridge is \"actively monitored by security.\"",
  "A hiring manager who demands a \"rockstar coder\" but refuses to provide a laptop.",
  "An applicant who sends a LinkedIn message saying \"I know where you live\" after getting rejected.",
  "A candidate who lists \"Professional Witness\" under past work experience.",
  "An interviewer who keeps calling the candidate by the wrong name for an hour.",
  "A candidate who claims they left their last job due to \"philosophical differences with gravity.\"",
  "An applicant who submits a 40-page autobiography instead of a resume.",
  "A hiring manager who rejects a candidate for wearing the wrong shade of blue.",
  "A candidate who asks if the company's background check covers \"minor international incidents.\"",
  "An applicant who attempts to negotiate their salary using a PowerPoint deck.",
  "An interviewer who takes a personal call during the technical portion of the interview.",
  "A candidate who lists \"Competitive Eating\" under relevant skills for a finance role.",
  "An applicant who claims to have invented the concept of \"teamwork.\"",
  "A candidate who asks if the job requires \"a lot of heavy lifting or emotional labor.\"",
  "An interviewer who asks \"What is your biggest fear?\" and takes notes aggressively.",
  "A candidate who submits a resume written entirely in wingdings.",
  "An applicant who shows up to an interview wearing a full tracksuit.",
  "A hiring manager who insists on doing the interview while walking on a treadmill desk.",
  "A candidate who asks if the company has a policy on \"office hauntings.\"",
  "An applicant who lists \"Fluent in sarcasm\" as their primary language.",
  "A candidate who tries to bribe the recruiter with a 50-dollar Amazon gift card.",
  "An interviewer who spends the entire time complaining about their own manager.",
  "A candidate who claims to have 20 years of experience in a technology created yesterday.",
  "An applicant who lists \"Master of Deception\" under their qualifications.",
  "A candidate who asks if the office is \"surveillance-free.\"",
  "An interviewer who asks the candidate to sell them a broken pen.",
  "A candidate who brings their life coach to the salary negotiation.",
  "An applicant who lists \"Professional Apologizer\" as a previous job title.",
  "A hiring manager who rejects a candidate because they didn't order coffee at the café interview.",
  "A candidate who asks if the company offers \"mental health days for hangovers.\"",
  "An applicant who submits a video resume that is just a montage of them working out.",
  "A candidate who lists \"Expert in Office Gossip\" as a soft skill.",
  "An interviewer who reads the candidate's resume for the first time during the interview.",
  "A candidate who asks if the company allows \"unannounced sabbaticals.\"",
  "An applicant who claims to be \"overqualified for basic reality.\"",
  "A candidate who lists their parents as their professional references.",
  "An interviewer who uses a magic 8-ball to make hiring decisions.",
  "A candidate who asks if the workplace is \"vibe-checked\" regularly.",
  "An applicant who submits a resume that is just a list of buzzwords in alphabetical order.",
  "A candidate who asks if the company has a union while sitting next to the CEO.",
  "An interviewer who asks \"Why should we hire you when we could hire AI?\"",
  "A candidate who lists \"Professional Boundary Pusher\" under achievements.",
  "An applicant who brings a guitar to the interview and insists on singing their cover letter.",
  "A candidate who asks if the company's health insurance covers \"spiritual healing.\"",
  "An interviewer who judges candidates based on their choice of web browser.",
  "A candidate who claims to have single-handedly saved their previous company from bankruptcy.",
  "An applicant who lists \"Master of the Pivot\" after changing jobs 12 times in one year.",
  "A candidate who asks if the office is \"pet-friendly for venomous snakes.\"",
  "An interviewer who asks \"How many golf balls can fit in a school bus?\" in 2026.",
  "A candidate who submits a cover letter that is just a series of memes.",
  "An applicant who lists \"Professional Cryptic Email Writer\" as a core strength.",
  "A candidate who asks if the salary is \"negotiable based on my lifestyle needs.\"",
  "An interviewer who accidentally shares their screen showing a document titled \"Candidates to Reject.\"",
  "A candidate who lists \"Expert in avoiding work\" and claims it demonstrates efficiency.",
  "A candidate who answers a coding challenge using pseudo-code and pure optimism.",
  "An applicant who lists \"Master of passive-aggressive email signatures\" as a core strength.",
  "A hiring manager who rejects someone because their LinkedIn profile picture looks \"too happy.\"",
  "Answering \"What is your dream job?\" with \"Not working.\"",
  "A candidate who insists on taking the interview from the driver's seat of a moving Tesla.",
  "An applicant who lists \"Certified Corporate Survivalist\" on their CV.",
  "A candidate who asks if the company has a policy against \"light workplace espionage.\"",
  "An interviewer who spends 20 minutes explaining why the company is like a \"high-performing sports team.\"",
  "A candidate who cites their high-school debate record to dispute salary data.",
  "An applicant who attaches a 10-minute video rant about their former boss as an extra reference.",
  "A candidate who claims they can \"turn any red flag into a teachable moment.\"",
  "An interviewer who visibly sighs every time the candidate mentions work-life balance.",
  "A candidate who lists \"Professional Chaos Coordinator\" without a trace of irony.",
  "An applicant who submits a resume printed on scented paper like \"Legally Blonde.\"",
  "Asking if the office has \"crying rooms\" during the facility tour.",
  "A hiring manager who insists on testing a candidate's \"grit\" by making them wait in a cold room.",
  "A candidate who refers to their previous employment gap as a \"stealth-mode personal sprint.\"",
  "An applicant who tries to negotiate for an extra week of vacation before even getting phone screened.",
  "A candidate who lists \"Expert in nodding during Zoom calls while completely zoned out.\"",
  "An interviewer who asks \"How do you handle conflict?\" while actively picking a fight.",
  "A candidate who brings their twin sibling to take the technical assessment for them.",
  "An applicant who lists \"Proficient in maintaining eye contact until people feel uncomfortable.\"",
  "A candidate who asks if the company's background check looks into deleted Reddit accounts.",
  "An interviewer who marks a candidate down for having an \"uninspiring\" background blur.",
  "A candidate who addresses the panel as \"Listen up, squad.\"",
  "An applicant who lists \"Crisis Avoidance\" because they hid in the breakroom during an audit.",
  "A candidate who demands to see the hiring manager's performance review before proceeding.",
  "An interviewer who uses a literal stopwatch to time candidate responses.",
  "A candidate who claims to be a \"human algorithm\" for business growth.",
  "An applicant who submits a resume that is just a link to their Spotify playlist.",
  "A candidate who asks if the company provides \"emotional hazard pay.\"",
  "An interviewer who accidentally forwards internal salary notes directly to the candidate.",
  "A candidate who lists \"Master of the 4:59 PM log-off\" as a personal achievement.",
  "An applicant who asks if the team's \"work hard, play hard\" motto involves actual play.",
  "A candidate who answers every behavioral question with a story about their fantasy football league.",
  "An interviewer who asks \"Where do you see us in five years?\"",
  "A candidate who lists \"Unmatched stamina for useless meetings\" as their top technical skill.",
  "An applicant who arrives to a video interview wearing a full VR headset.",
  "A hiring manager who rejects candidates based on their email domain provider.",
  "A candidate who asks if \"overtime\" means actual hours or just a general state of mind.",
  "An applicant who lists \"Professional Ghoster\" after ignoring three follow-up calls.",
  "A candidate who insists on answering panel questions through a puppet.",
  "An interviewer who claims \"we don't believe in burn-out here, only momentum.\"",
  "A candidate who lists \"Expert in delegating work back to the person who assigned it.\"",
  "An applicant who asks if the company's \"flexible hours\" allow for working exclusively at night.",
  "A candidate who claims their top skill is \"managing manager expectations downwards.\"",
  "An interviewer who falls for a candidate's completely fabricated industry awards.",
  "A candidate who lists \"Advanced proficiency in Slack emoji reactions\" on their resume.",
  "An applicant who asks if the salary package includes coverage for \"existential dread.\"",
  "A candidate who ends the interview by saying \"Don't call me, I'll call you.\"",
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { BLACK_CARDS, WHITE_CARDS };
}
